NEW_CASES_SOURCE = r'''
  dict(title="EuroHomes", sub="CASE 10 · Real Estate · International property portal (buy abroad)", body=case_body(
    "CEO", "EuroHomes",
    "Онлайн-портал недвижимости, где покупатели ищут дома и квартиры в Испании, Италии и Португалии. Работает с местными агентствами, которые размещают объекты на платформе. Как Rightmove — но для покупки недвижимости за рубежом.",
    "В основном покупатели из UK, Германии и Нидерландов 40–65 лет, ищущие дом для отдыха, для переезда на пенсию или для инвестиций в Южной Европе.",
    "Подписки агентств (ежемесячная плата за размещение объектов) и оплата за лиды (когда покупатель связывается с агентом через сайт).",
    "На сайте 50 000 объявлений о недвижимости. Google индексирует и показывает лишь небольшую часть. Техническое агентство сказало про «проблему дублированного контента» — многие страницы слишком похожи друг на друга. Не понимают, что делать.",
    "Из недвижимости, не из tech. Важны лиды и подписки агентств.",
    "Hello. We run a website where people can search for properties to buy in Spain, Italy and Portugal. We have around fifty thousand property listings — they update automatically from agent feeds. Our problem is that Google seems to index only a small percentage of our listings. Also, many of our listing pages look very similar to each other — same template, just different address and price. A technical SEO agency told us we have a 'duplicate content problem'. What does that mean? And how do we get Google to properly index and rank our property pages?",
    ["If we have fifty thousand pages, does Google visit all of them?",
     "What is a canonical tag? Our developer mentioned it but I don't understand the purpose.",
     "Some of our listings expire when properties are sold — should we delete those pages?",
     "Our competitor Rightmove has millions of pages and they rank fine. How do they do it?"],
    ["duplicate content","crawl budget","canonicalization","programmatic SEO","faceted navigation","expired listings strategy","internal linking at scale","indexing prioritisation"],
    "ℹ️ 50k страниц — programmatic SEO задача. Canonical, уникальный контент на шаблонных страницах, crawl budget management, стратегия expired listings (301 или aggregate). Rightmove = DR + unique UGC + established authority.",
  )),
  dict(title="Sterling Immigration", sub="CASE 11 · Legal services · Immigration law firm (3 UK офиса)", body=case_body(
    "Head of Business Development", "Sterling Immigration",
    "Юридическая фирма по иммиграции с офисами в Лондоне, Манчестере и Бирмингеме. Помогает с визами в UK, гражданством, ILR и иммиграционными апелляциями. Юристы — квалифицированные солиситоры, регулируемые SRA.",
    "Люди, подающие на визы UK (skilled worker, spouse, student), компании-спонсоры зарубежных сотрудников, и те, кто оспаривает иммиграционные решения.",
    "Фиксированная оплата за кейс — обычно £1,500–£5,000 в зависимости от сложности.",
    "Почти все клиенты приходят по рекомендациям или через дорогую рекламу в Google. Полгода вели блог о разных типах виз — почти нет трафика. Не понимают, почему стратегия не работает.",
    "Юридический бэкграунд, не digital. Осторожный и не любит риск по натуре. Важны новые обращения и объём кейсов.",
    "Good afternoon. We are an immigration law firm with offices in London, Manchester and Birmingham. We help people with UK visas, citizenship applications, and immigration appeals. Right now almost all our clients come from referrals or we pay a lot for Google Ads. We want to be found organically when someone searches 'immigration lawyer London' or 'UK visa help'. We tried blogging for six months — we wrote about different visa types — but we get almost no traffic. What are we doing wrong?",
    ["Should each of our three offices have its own page on the website?",
     "We are worried about publishing legal advice online — what if someone relies on wrong information?",
     "Our blog articles are about three hundred words each. Is that too short?",
     "There is a legal directory called Chambers — does being listed there help our SEO?"],
    ["local SEO for professional services","practice area pages","YMYL (legal)","E-E-A-T","content depth","location landing pages","legal directories as citations"],
    "ℹ️ Law firm SEO = local SEO + YMYL E-E-A-T. Три офиса → три location pages. 300 слов — катастрофически мало для юридической ниши (нужно 1500-3000). Chambers/Legal 500 — авторитетные citations. Disclaimer решает проблему страха перед публичными советами.",
  )),
  dict(title="CoinBridge Exchange", sub="CASE 12 · Crypto · Centralised exchange", body=case_body(
    "Chief Marketing Officer", "CoinBridge Exchange",
    "Регулируемая платформа для покупки, продажи и хранения криптовалют (Bitcoin, Ethereum). Как фондовая биржа — но для цифровых валют.",
    "Розничные инвесторы и крипто-энтузиасты, в основном в Европе, которые хотят покупать Bitcoin без крупных платформ вроде Coinbase.",
    "Комиссия 0.1–0.5% с каждой сделки пользователя.",
    "Когда команда спрашивает ChatGPT или Perplexity «какую крипто-биржу выбрать?», ответ всегда рекомендует Binance и Coinbase. Бренд не упоминается никогда — хотя биржа лицензирована, безопасна и с конкурентными комиссиями.",
    "Лично пользуется крипто, понимает продукт, но ничего не знает о работе Google или AI-инструментов. Важны новые регистрации пользователей.",
    "Good morning. We operate a crypto exchange — we have been live for two years. When our customers ask ChatGPT or Perplexity which exchange to use, the answer is always Binance or Coinbase. Our brand is never mentioned. Not once. We have good reviews on Trustpilot and we are regulated in Estonia. What can we do to appear in AI-generated answers? And is this even possible, or do only the biggest brands get mentioned?",
    ["What is the connection between Google rankings and being mentioned by AI?",
     "We have a blog but we mostly write about crypto news. Is that the wrong strategy?",
     "Someone told us to get mentions on Reddit and crypto forums. Does that actually help?",
     "How would you measure success — how do we know if it's working?"],
    ["AEO","LLM visibility","brand entity","E-E-A-T","third-party mentions","topical authority","structured data","AI answer engines"],
    "ℹ️ Спец должен объяснить: AI берёт данные из авторитетных источников — Wikipedia, Reddit, топ Google. SEO + digital PR + entity building — это путь к LLM visibility. Измеримость: Brand Radar, ручное тестирование промптов.",
  )),
  dict(title="PayFast", sub="CASE 13 · Fintech · B2B payment gateway (стартап, 8 месяцев)", body=case_body(
    "Co-Founder", "PayFast",
    "Сервис обработки платежей для интернет-магазинов. Если магазин одежды или SaaS-компания хочет принимать оплату картой от клиентов по всему миру — используют PayFast. Обрабатывают платежи в 30 валютах с комиссией ниже, чем у Stripe или PayPal.",
    "E-commerce бизнесы и SaaS-стартапы — обычно малые и средние компании, продающие онлайн.",
    "Комиссия 0.8% + £0.20 с каждой транзакции клиента-мерчанта.",
    "Запустились 8 месяцев назад. Продукт конкурентный, но почти никто не находит через Google. По запросам вроде «best payment gateway for e-commerce» сайта нет нигде — ни на первой, ни на второй странице. Отличная технология, но нулевая органическая видимость.",
    "Технический фаундер — сам строил продукт. Growth-маркетинг и SEO — новая территория. Важны регистрации мерчантов и объём транзакций.",
    "Good afternoon. We launched a payment gateway for e-commerce businesses eight months ago. We process payments in thirty currencies and our fees are lower than Stripe or PayPal. But when someone searches 'best payment gateway for e-commerce', we are not in the results. Not on page one, not on page two. Our website gets almost no organic traffic at all. We are a new company — is it even possible to rank for these terms? Or do we need to wait years before SEO can help us?",
    ["What is domain authority and why does our new site have a disadvantage?",
     "Should we focus on very specific keywords first instead of competitive ones?",
     "A consultant told us to buy five hundred backlinks. Is that a good idea?",
     "What would you do in the first three months if you were working on our project?"],
    ["domain authority","long-tail strategy","topical authority","digital PR","keyword difficulty","link building for startups","quick wins"],
    "ℹ️ Новый домен — реальный challenge. Стратегия: long-tail + low competition ниши сначала, параллельно digital PR для ссылок. 500 купленных ссылок для fintech — риск manual penalty. Честные сроки: 6-18 месяцев.",
  )),
  dict(title="Moda Linen", sub="CASE 14 · E-commerce · DTC fashion brand (США, 3000 SKU)", body=case_body(
    "Head of E-commerce", "Moda Linen",
    "Собственный бренд женской одежды — дизайн in-house, производство в Португалии. Продажи полностью через свой сайт, в основном клиентам в США. Стиль минималистичный, на основе льна, устойчивый. Около 3000 карточек товаров.",
    "Американки 28–45 лет, ценящие качество, устойчивость и минималистичную моду. Часто ищут в Google «linen summer dresses» или «minimalist women's clothing».",
    "Прямые продажи товаров с маржой 55–70%. Плюс Google Shopping и реклама в Instagram.",
    "Позиции по запросам вроде «linen dresses» и «minimalist fashion» заметно упали за последние 4 месяца. Google ведёт себя непоследовательно — то показывает страницы категорий, то карточки товаров по одному и тому же запросу. Расходы на рекламу растут, потому что упал органический трафик.",
    "Хорошо разбирается в моде и ритейле, понимает клиента, но техническое SEO — новая территория. Важны выручка сайта и ROAS.",
    "Hi. We sell women's clothing online — our own brand, made in Portugal, sold mainly in the US. We have about three thousand product pages. New collections come in every season, so old products go out of stock. Our problem: we used to rank well for terms like 'linen dresses' or 'minimalist fashion'. In the last four months our rankings for those terms dropped significantly. We also noticed that Google sometimes shows our category pages, sometimes product pages — it's inconsistent. What is happening and how do we stabilise our rankings?",
    ["What should we do with product pages when items go out of stock permanently?",
     "What is keyword cannibalization? Could that be our problem?",
     "Our product descriptions are about eighty words each. Is that enough?",
     "We have three thousand products — do we need unique content on every single page?"],
    ["keyword cannibalization","category vs product page hierarchy","out-of-stock strategy","faceted navigation","thin content at scale","collection page optimisation","product schema"],
    "ℹ️ Каннибализация category vs product pages — классика e-com. Category pages должны быть основными ranking pages. Out-of-stock: 301 на category или noindex. 80 слов = thin content. Приоритет: обогатить category pages.",
  )),
  dict(title="La Piazza Group", sub="CASE 15 · Local SEO · Italian restaurant group (5 точек, Лондон) · Reserve", body=case_body(
    "Co-Owner", "La Piazza Group",
    "Пять итальянских ресторанов в разных районах Лондона: Сохо, Ислингтон, Кэнэри-Уорф, Брикстон и Уимблдон. Каждый ресторан подаёт традиционную итальянскую кухню — пасту, пиццу, ризотто — на обед и ужин. У каждой точки своя команда и немного отличное меню.",
    "Местные жители, офисные работники и туристы, ищущие настоящую итальянскую еду. Большинство находят рестораны через Google Maps.",
    "Средний чек за столик (обед и ужин) и частные мероприятия — дни рождения, корпоративы.",
    "При поиске итальянских ресторанов в Google Maps рестораны иногда появляются, иногда нет. Точка в Брикстоне открыта три года, отличная еда и хорошие отзывы — но почти не видна. Более новый конкурент открылся полгода назад рядом и уже ранжируется выше. Также у точки в Кэнэри-Уорф в Google-профиле указаны неверные часы работы, которые они не устанавливали.",
    "Увлечённый ресторатор, разбирается в еде и гостеприимстве. Digital-маркетинг — не его мир. Важны число столиков за вечер и брони мероприятий.",
    "Hello. I own five Italian restaurants in London — Soho, Islington, Canary Wharf, Brixton, and Wimbledon. When I search Google Maps for Italian restaurants in each area, my restaurants sometimes appear and sometimes they don't. Our Brixton location has been open for three years and we have great food and good reviews. But it barely shows up on Google Maps. A place that opened six months ago near us appears in the top three. I also noticed that our Google listing for Canary Wharf shows the wrong opening hours — I didn't change that. What controls which restaurants Google shows? And why is a newer place beating us?",
    ["We have 4.2 stars with two hundred Google reviews. Is that not enough?",
     "What is the difference between appearing on Google Maps and appearing in regular Google search results?",
     "Should each restaurant have its own website, or is one website with five pages fine?",
     "Someone told us to reply to all our reviews — does that actually affect our rankings?"],
    ["local pack","Google Business Profile","proximity/relevance/prominence","review velocity","NAP consistency","GBP optimisation","location pages","local citations","GBP spam (wrong info)"],
    "ℹ️ Три фактора local pack: proximity, relevance, prominence. Неправильные часы в GBP — можно оспорить через GBP support. Отдельная location page для каждого ресторана обязательна. Ответы на отзывы — влияют на prominence сигнал.",
  )),
  dict(title="ShieldVPN", sub="CASE 16 · SaaS · VPN & privacy tool · Reserve (Reddit & LLM)", body=case_body(
    "Chief Marketing Officer", "ShieldVPN",
    "VPN-сервис. Приложение шифрует интернет-соединение и скрывает реальное местоположение пользователя. Люди используют его для приватности, доступа к стриминг-контенту из других стран, безопасности в публичном wifi. Конкурирует с NordVPN, Mullvad и ExpressVPN.",
    "Люди, заботящиеся о приватности, удалённые сотрудники, журналисты и жители стран с интернет-ограничениями. Обычно довольно tech-savvy аудитория.",
    "Ежемесячная или годовая подписка — обычно £5–£12 в месяц.",
    "Протестировали вопрос ChatGPT «какой VPN лучший для приватности?». Ответ рекомендовал NordVPN, Mullvad и ProtonVPN — и цитировал обсуждение с Reddit r/privacy как источник. В этом треде конкурент Mullvad упомянут 40+ раз. Бренд — ни разу. Тот же тред на Google — на 2-м месте по запросу «best privacy VPN». Конкурент получает и трафик Google, и рекомендации от ИИ — а они не получают ничего.",
    "Сам разбирается в privacy-технологиях, маркетинг-ориентирован, но не SEO-специалист. Важны рост подписчиков и отток (churn).",
    "Hi. We make a VPN product — we have been on the market for four years. Recently I tested something. I asked ChatGPT: 'What is the best VPN for privacy?' The answer mentioned NordVPN, Mullvad, and ProtonVPN. It quoted a Reddit thread from r/privacy. In that Reddit thread, our competitor Mullvad is mentioned over forty times. We are not mentioned once. I also checked — that Reddit thread ranks number two on Google for 'best privacy VPN'. So our competitor gets Google traffic, gets cited by AI, and we are invisible on both. What do we do?",
    ["Can we just go to Reddit and post about our product ourselves?",
     "Why do LLMs like ChatGPT use Reddit as a source? Isn't it just random people talking?",
     "If we get mentioned on Reddit, how long before ChatGPT starts recommending us?",
     "What is the difference between Reddit strategy and normal link building?"],
    ["Reddit SEO","LLM citation sources","UGC signals","brand mentions","community seeding","AEO","subreddit authority","share of voice"],
    "ℹ️ Reddit ранжируется в Google И является источником для LLM. Стратегия: органическое присутствие (ценные комментарии, не спам), digital PR, entity building. Это долго и нельзя купить быстро.",
  )),
  dict(title="SpendSmart", sub="CASE 17 · Fintech · Personal budgeting app · Reserve (Reddit & LLM)", body=case_body(
    "CEO", "SpendSmart",
    "Мобильное приложение для управления личными финансами — учёт расходов по категориям, цели накоплений, напоминания об оплате счетов. Доступно на iOS и Android. Как персональный финансовый коуч в кармане.",
    "Взрослые 22–40 лет в США и UK, желающие контролировать финансы, копить или выплатить долги. Часто молодые специалисты и семьи.",
    "Подписка £5/месяц или £40/год после бесплатного пробного периода.",
    "Протестировали несколько AI-инструментов. На вопрос «лучшее приложение для бюджета» ИИ рекомендует YNAB, а источники — треды Reddit r/personalfinance. У приложения рейтинг в App Store выше, чем у YNAB — 4.8 против 4.6. Но в AI-рекомендациях и на Reddit его просто не существует.",
    "Продуктовый фаундер — построил отличное приложение, но понимает, что этого недостаточно. Важны загрузки приложения и конверсия в платную подписку.",
    "Hello. We make a personal finance app — budget tracking, savings goals, bill reminders. Our main competitor is YNAB. I checked what happens when people ask Perplexity: 'best budgeting app'. Perplexity shows a summary and then links to three Reddit threads — all from r/personalfinance. In those threads, YNAB is the top recommendation in almost every comment. We appear maybe twice. Our app has better App Store reviews than YNAB. But in AI answers we basically don't exist. How is it possible that Reddit controls what AI recommends — and what can we do about it?",
    ["We have real customers who love our app — can we ask them to post on Reddit?",
     "YNAB has been around longer. Is this just about brand age?",
     "If I search our brand name on Reddit, there are almost no posts. Is that the problem?",
     "What would success look like in six months — how do we measure Reddit and AI visibility?"],
    ["Reddit share of voice","LLM recommendation sources","brand entity","community-led growth","Reddit seeding strategy","AEO","unprompted brand mentions","AI visibility tracking"],
    "ℹ️ App Store reviews ≠ LLM visibility. LLM берёт из Reddit, форумов, авторитетных медиа. Стратегия: Reddit присутствие + digital PR + brand упоминания. Просить клиентов писать на Reddit — риск бана.",
  )),
'''
