# -*- coding: utf-8 -*-
from build import page, section, table_scroll, phrase_card, phrase_grid, accordion, write

# ---------- 1. Vocabulary table ----------
vocab_headers = ["Term", "Произношение", "Definition (EN)", "Перевод (RU)", "Example"]
vocab_rows = [
    ("★ Upsell", "апсэл",
     "To offer a client a more expensive or expanded version of the same service.",
     "Предложить клиенту более дорогой / расширенный вариант той же услуги.",
     "&ldquo;We could upsell them to the premium content package.&rdquo;"),
    ("★ Cross-sell", "кросс-сэл",
     "To offer a separate, additional service alongside the current one.",
     "Предложить дополнительную, отдельную услугу.",
     "&ldquo;This is a good opportunity to cross-sell our CRO audit.&rdquo;"),
    ("Add-on service", "эд-он сёрвис",
     "An extra service that supplements the base package.",
     "Дополнительная услуга сверх основного пакета.",
     "&ldquo;Link building is an add-on to the base SEO package.&rdquo;"),
    ("Scope expansion", "скоуп экспэншн",
     "An increase in the amount or type of work being done.",
     "Расширение объёма или типа выполняемых работ.",
     "&ldquo;We need to formalize this scope expansion in a new contract.&rdquo;"),
    ("★ Retainer increase", "ритэйнэр инкриз",
     "A rise in the client's fixed monthly budget.",
     "Увеличение фиксированного ежемесячного бюджета клиента.",
     "&ldquo;Given the results, a retainer increase makes sense.&rdquo;"),
    ("Bundle", "бандл",
     "A package of several services sold together, usually at a discount.",
     "Пакет из нескольких услуг, продаваемых вместе, обычно со скидкой.",
     "&ldquo;We offer a bundle: SEO + content + digital PR.&rdquo;"),
    ("Value-based pricing", "вэлью-бэйзд прайсинг",
     "Pricing based on the projected business value/ROI, not hours worked.",
     "Цена, основанная на прогнозируемой ценности / ROI, а не на потраченных часах.",
     "&ldquo;We price this based on projected ROI, not hours.&rdquo;"),
    ("Pilot project", "пайлот проджект",
     "A small trial project before scaling something up.",
     "Небольшой пробный проект перед масштабированием.",
     "&ldquo;Let's start with a pilot project on 10 pages.&rdquo;"),
    ("★ Warm lead", "уорм лид",
     "A client who is already mentally ready to buy — they've shown interest.",
     "Клиент, который уже морально готов купить — уже проявлял интерес.",
     "&ldquo;They're a warm lead — they already asked about content.&rdquo;"),
    ("Renewal", "ринюал",
     "The point at which a contract is extended for another period.",
     "Момент продления контракта на новый период.",
     "&ldquo;Renewal is coming up in Q3 — good moment to discuss growth.&rdquo;"),
]
vocab_table = table_scroll(vocab_headers, vocab_rows)
vocab_note = '<p class="note">★ — приоритетные термины для клиентских звонков</p>'
vocab_sec = section("vocab", "Upselling Vocabulary · Словарь", "★ = самые важные для клиентских звонков",
                     vocab_table + vocab_note)

# ---------- 2. Key phrases for natural upselling ----------
cat_a = phrase_card("A. Опираясь на результат (leveraging results)", [
    ("Since we're already seeing strong results with X, this might be a good time to look at Y.",
     "Раз мы уже видим сильные результаты по X, возможно, сейчас хороший момент посмотреть на Y."),
    ("Given the growth we're seeing in organic traffic, have you thought about expanding into content marketing?",
     "Учитывая рост органического трафика, вы думали о расширении в контент-маркетинг?"),
    ("One thing that could accelerate results even further is…",
     "Одна вещь, которая могла бы ускорить результаты ещё сильнее — это…"),
])
cat_b = phrase_card("B. Мягкий переход к продаже (soft framing)", [
    ("While we're on the call, I wanted to flag an opportunity.",
     "Пока мы на связи, хотел отметить одну возможность."),
    ("This isn't something you need right now, but it's worth having on your radar.",
     "Это не то, что нужно прямо сейчас, но стоит иметь в виду."),
    ("No pressure at all — just wanted to put this on your radar.",
     "Совсем без давления — просто хотел, чтобы вы держали это в уме."),
])
cat_c = phrase_card("C. Обработка возражений (handling pushback)", [
    ("I understand budget's tight right now — we could start smaller with a pilot.",
     "Понимаю, что бюджет сейчас ограничен — можем начать с меньшего пилотного формата."),
    ("Totally fair question — here's how this pays for itself over time.",
     "Совершенно справедливый вопрос — вот как это окупается со временем."),
    ("Let's revisit this next quarter once we've locked in the current results.",
     "Давайте вернёмся к этому в следующем квартале, когда закрепим текущие результаты."),
])
cat_d = phrase_card("D. Мягкое закрытие (soft close)", [
    ("Would it make sense to set up a quick call to walk through the numbers?",
     "Есть ли смысл назначить короткий звонок, чтобы пройтись по цифрам?"),
    ("Should I put together a one-page so you can share it internally?",
     "Подготовить короткую сводку, чтобы вы могли показать её внутри команды?"),
])
phrases_sec = section("phrases", "Key Phrases for Natural Upselling", "4 модели фраз для органичного апсейла на звонке",
                       phrase_grid([cat_a, cat_b, cat_c, cat_d]))

# ---------- 3. Roleplay scenarios ----------
def scenario_body(niche, context, spec_role, client_role, spec_phrases, client_phrases=None):
    sp = "".join(f'<blockquote class="script">{en}<br><span class="ru">{ru}</span></blockquote>' for en, ru in spec_phrases)
    parts = [
        f'<p class="idea"><strong>Ниша:</strong> {niche}</p>',
        f'<p class="idea"><strong>Контекст:</strong> {context}</p>',
        f'<h5>Роль специалиста</h5><p>{spec_role}</p>',
        f'<h5>Роль клиента</h5><p>{client_role}</p>',
        f'<h5>Фразы-помощники · специалист</h5>{sp}',
    ]
    if client_phrases:
        cp = "".join(f'<blockquote class="script">{en}<br><span class="ru">{ru}</span></blockquote>' for en, ru in client_phrases)
        parts.append(f'<h5>Фразы-помощники · клиент</h5>{cp}')
    else:
        parts.append('<p class="idea"><em>Фразы клиента для этого сценария в материалах не сохранились — импровизируйте на основе роли клиента выше.</em></p>')
    return "".join(parts)

scenarios = [
  dict(title="The Link Gap", sub="A · Расширение каналов · линкбилдинг, рост бюджета", body=scenario_body(
    "E-commerce — онлайн-магазин одежды",
    "6 месяцев работы, трафик стабилен, но топ-3 конкурента обгоняют в первую очередь за счёт Domain Rating — у них в 2 раза больше качественных ссылок. Текущий бюджет на линкбилдинг — $800/мес, outreach даёт всего 2–3 ссылки в месяц.",
    "Показать разрыв в ссылочном профиле у конкурентов, объяснить, что рост позиций ограничен именно ссылками, предложить увеличить бюджет с $800 до $2 500/мес.",
    "E-commerce Marketing Director, ROI-driven. Хочет видеть прямую связь ссылок с продажами, ссылки кажутся «непонятной» статьёй расходов по сравнению с рекламой.",
    [("When we benchmark against your top 3 competitors, the biggest gap isn't content — it's link authority.",
      "Когда мы сравниваем вас с топ-3 конкурентами, главный разрыв не в контенте — а в ссылочном авторитете."),
     ("Right now we're getting 2-3 links a month; to close the gap, we'd need to at least triple that pace.",
      "Сейчас мы получаем 2-3 ссылки в месяц; чтобы закрыть разрыв, нужно как минимум утроить темп."),
     ("Links compound over time — the ROI shows up in 3-6 months, not immediately.",
      "Ссылки работают накопительно — ROI проявляется через 3-6 месяцев, а не сразу."),
     ("We could start with a 3-month test at the higher budget and measure the ranking lift directly.",
      "Можем начать с 3-месячного теста на повышенном бюджете и напрямую замерить рост позиций."),
     ("I can show you the correlation between DR growth and ranking movement for pages we've already built links to.",
      "Могу показать корреляцию между ростом DR и изменением позиций на страницах, где мы уже строили ссылки.")],
    [("How do I know it's the links and not something else holding us back?",
      "Как мне узнать, что дело именно в ссылках, а не в чём-то другом?"),
     ("Links feel like a black box compared to ads — I can't see a direct sale from a link.",
      "Ссылки кажутся «чёрным ящиком» по сравнению с рекламой — я не вижу прямой продажи от ссылки."),
     ("Can we test this on a smaller budget first?",
      "Можем протестировать на меньшем бюджете сначала?"),
     ("What happens if we increase the budget and rankings still don't move?",
      "Что если мы увеличим бюджет, а позиции всё равно не сдвинутся?"),
     ("Our competitors might just have a bigger brand, not more links.",
      "Может, у конкурентов просто бренд сильнее, а не больше ссылок.")],
  )),
  dict(title="Traffic Without Pipeline", sub="A · Расширение каналов · CRO-аудит", body=scenario_body(
    "SaaS — платформа для найма",
    "Органический трафик вырос на 65% за год, но конверсия в demo request остаётся на уровне 0.8%. Специалист заметил через аналитику явные проблемы на посадочных страницах.",
    "Показать, что SEO уже привело достаточно трафика, и следующая точка роста — конверсия. Предложить CRO-аудит как отдельный add-on, не входящий в текущий SEO-пакет.",
    "Head of Marketing, трафик-ориентированный. Считает, что задача агентства — приводить трафик, а разбираться с конверсией — работа продукта/дизайна.",
    [("We're now bringing in 3x the traffic we started with — but conversion rate hasn't moved.",
      "Сейчас мы приводим в 3 раза больше трафика, чем в начале — но конверсия не сдвинулась."),
     ("At this point, more traffic without fixing conversion is diminishing returns.",
      "На этом этапе больше трафика без исправления конверсии — это уменьшающаяся отдача."),
     ("A CRO audit would look at exactly where visitors drop off before requesting a demo.",
      "CRO-аудит покажет ровно в какой момент посетители уходят до запроса демо."),
     ("This isn't scope creep — it's making sure the traffic we generate actually turns into pipeline.",
      "Это не расширение объёма работ — это гарантия, что трафик реально превращается в pipeline."),
     ("We can start with a lightweight audit on your top 5 landing pages.",
      "Можем начать с лёгкого аудита топ-5 посадочных страниц.")],
    [("Isn't conversion a design/product problem, not an SEO problem?",
      "Разве конверсия не проблема дизайна/продукта, а не SEO?"),
     ("We already pay a UX agency for that — why would we need you too?",
      "Мы уже платим UX-агентству за это — зачем нам ещё и вы?"),
     ("How do we know this isn't just you trying to bill more hours?",
      "Как узнать, что вы не просто пытаетесь набить больше часов?"),
     ("What's the actual expected lift in demo requests?",
      "Какой реально ожидаемый рост запросов на демо?"),
     ("Can you just send recommendations instead of a paid audit?",
      "Можете просто прислать рекомендации без платного аудита?")],
  )),
  dict(title="The Bad Review on Page One", sub="B · Новые направления · SERM", body=scenario_body(
    "Сеть стоматологических клиник (&laquo;SmileCare Clinics&raquo;)",
    "У одной из клиник сети появилось несколько негативных отзывов и статья на форуме, которая ранжируется на первой странице по брендовому запросу. Владелец сети обеспокоен, что новые пациенты видят это первым.",
    "Объяснить, что это отдельная услуга (SERM), не входящая в текущий SEO-пакет. Предложить план: продвижение позитивных страниц, работа с отзывами, мониторинг брендовой выдачи.",
    "Owner, эмоционально вовлечён, немного паникует. Хочет, чтобы негатив «просто исчез» быстро, путает SERM с «накруткой отзывов» или «удалением через жалобы».",
    [("We can't remove that article, but we can make sure it's not the first thing people see.",
      "Мы не можем удалить статью, но можем сделать так, чтобы она не была первым, что видят люди."),
     ("SERM is about outranking negative content with strong, positive brand pages — not deleting anything.",
      "SERM — это про то, чтобы обгонять негативный контент сильными позитивными страницами, а не удалять что-то."),
     ("This sits outside our current SEO scope, so it would be a separate monthly package.",
      "Это выходит за рамки текущего SEO-пакета, поэтому будет отдельным ежемесячным пакетом."),
     ("We'd also set up ongoing monitoring so we catch anything like this early next time.",
      "Мы также настроим постоянный мониторинг, чтобы ловить такое раньше в следующий раз."),
     ("Fake reviews or forced takedowns would actually make this worse — let's do this the sustainable way.",
      "Фейковые отзывы или принудительное удаление только всё усугубят — сделаем это устойчивым способом.")],
  )),
  dict(title="The Content Gap", sub="B · Новые направления · контент-ретейнер", body=scenario_body(
    "Юридическая компания (&laquo;Harlow &amp; Reeves Law&raquo;)",
    "SEO стабильно даёт трафик по транзакционным запросам, но у сайта почти нет блога — упускаются информационные запросы, которые конкуренты закрывают контентом и получают AI-цитирования.",
    "Показать пробел в контенте по сравнению с конкурентами, предложить ежемесячный контент-ретейнер (2–4 статьи в месяц) как add-on.",
    "Managing Partner, консервативен, ценит только лиды. Считает, что «статьи это не то, за что клиенты платят».",
    [("Right now we're only capturing people who already know they need a lawyer — not people just starting to search.",
      "Сейчас мы захватываем только тех, кто уже знает, что нужен юрист — не тех, кто только начинает искать."),
     ("Your competitors are answering these questions and showing up in AI Overviews because of it.",
      "Ваши конкуренты отвечают на эти вопросы и поэтому появляются в AI Overviews."),
     ("This is a content retainer — 2 to 4 articles a month, targeting questions your future clients are actually asking.",
      "Это контент-ретейнер — 2-4 статьи в месяц, под вопросы, которые реально задают ваши будущие клиенты."),
     ("We can tie this directly to lead form submissions from those specific articles.",
      "Мы можем напрямую привязать это к заявкам с этих конкретных статей."),
     ("We'd start with a 3-month trial batch and track leads from that content specifically.",
      "Начнём с пробной партии на 3 месяца и отследим лиды именно с этого контента.")],
    [("How does a blog post turn into an actual client for us?",
      "Как статья в блоге превращается в реального клиента для нас?"),
     ("We tried a blog years ago and it didn't bring in cases.",
      "Мы пробовали блог много лет назад, и он не принёс дел."),
     ("Isn't this more of a marketing thing than an SEO thing?",
      "Разве это не больше маркетинг, чем SEO?"),
     ("Can we see this working for another law firm first?",
      "Можем увидеть, как это сработало для другой юрфирмы?"),
     ("How do we track ROI on articles specifically?",
      "Как мы конкретно отслеживаем ROI по статьям?")],
  )),
  dict(title="The Missing Mentions", sub="B · Новые направления · Digital PR", body=scenario_body(
    "Wellness-бренд натуральных добавок (&laquo;PureRoot Wellness&raquo;)",
    "Ссылочный профиль есть, но почти весь — от гостевых постов и каталогов, нет упоминаний в профильных изданиях. Конкуренты чаще цитируются в AI-ответах именно благодаря таким упоминаниям.",
    "Предложить Digital PR — кампанию по получению упоминаний/ссылок в профильных медиа через данные, исследования или экспертные комментарии. Бюджет — порядка $5 000.",
    "Founder, бюджет ограничен, PR кажется «непредсказуемым и дорогим». Предпочитает вложить деньги в то, что «точно сработает».",
    [("Right now almost all our links come from guest posts and directories — nothing from real editorial coverage.",
      "Сейчас почти все ссылки — от гостевых постов и каталогов, ничего от реальных изданий."),
     ("A single mention in a major health outlet is worth more for authority and AI citations than 50 guest posts.",
      "Одно упоминание в крупном издании о здоровье стоит больше для авторитета и AI-цитирований, чем 50 гостевых постов."),
     ("We'd package your customer data into a study journalists actually want to cover.",
      "Мы упакуем ваши данные о клиентах в исследование, которое журналисты действительно захотят осветить."),
     ("PR isn't guaranteed placement by placement, but the pattern over 6 months is very predictable.",
      "PR не гарантирует каждое отдельное размещение, но паттерн за 6 месяцев вполне предсказуем."),
     ("We can start with a smaller campaign around one data story and measure pickup before scaling.",
      "Можем начать с небольшой кампании вокруг одной инфоповода и замерить отклик до масштабирования.")],
    [("PR sounds expensive and unpredictable — how do we know we'll get anything out of it?",
      "PR звучит дорого и непредсказуемо — как узнать, что мы что-то получим?"),
     ("Can't we just keep doing guest posts, they're cheaper?",
      "Может, продолжим гостевые посты, они дешевле?"),
     ("What if journalists just ignore our pitch?",
      "А что если журналисты просто проигнорируют наш пич?"),
     ("How is this different from just paying for links?",
      "Чем это отличается от просто покупки ссылок?"),
     ("Can you guarantee at least a few placements?",
      "Можете гарантировать хотя бы пару размещений?")],
  )),
  dict(title="Five New Doors", sub="C · Экспансия · local SEO, новые локации", body=scenario_body(
    "Сеть фитнес-студий (&laquo;PowerFlex Studios&raquo;)",
    "SEO хорошо работает для 3 существующих студий, бренд открывает 5 новых локаций в других городах в течение полугода. Текущий пакет не включает работу с новыми Google Business Profile и локальным контентом для новых городов.",
    "Предложить расширение пакета под каждую новую локацию: GBP-оптимизация, локальные страницы, локальные ссылки/citations.",
    "Operations Director, фокус на открытии, не на маркетинге. Считает, что маркетинг подождёт и «само появится в Google».",
    [("Each new location needs its own optimized profile — it won't rank well by default.",
      "Каждой новой локации нужен свой оптимизированный профиль — по умолчанию она не будет ранжироваться."),
     ("The earlier we start on a new location's local SEO, the faster it ranks by opening day.",
      "Чем раньше мы начнём локальное SEO новой точки, тем быстрее она ранжируется к дню открытия."),
     ("This is priced per location, since each one needs its own citations and local content.",
      "Цена за локацию, потому что каждой нужны свои citations и локальный контент."),
     ("We've seen locations that skip this take 4-6 months longer to show up in the local map pack.",
      "Мы видели, что локации без этого появляются в локальной карте на 4-6 месяцев позже."),
     ("We can bundle all 5 new locations into one expanded package at a lower per-location rate.",
      "Можем объединить все 5 новых локаций в один расширенный пакет по более низкой цене за штуку.")],
    [("Won't Google just find the new locations automatically once we open?",
      "Разве Google не найдёт новые локации автоматически после открытия?"),
     ("Can this wait until after we've actually opened the doors?",
      "Это может подождать до самого открытия?"),
     ("Why does each location cost extra — isn't it the same work repeated?",
      "Почему каждая локация стоит дополнительно — разве это не одна и та же повторяющаяся работа?"),
     ("We're already spending a lot on the openings themselves.",
      "Мы уже тратим много на сами открытия."),
     ("Can we just do this ourselves with a template?",
      "Можем мы сами сделать это по шаблону?")],
  )),
  dict(title="The Satellite Play", sub="D · Стратегические сдвиги · сеть сателлитов", body=scenario_body(
    "Действующий SEO-клиент (ниша не указана)",
    "SEO-пакет работает 4 месяца, трафик и позиции стабильно растут. Специалист предлагает следующий шаг — сеть сателлитных сайтов (уже отработанный продукт, показавший результат у других клиентов): нишевые сайты-обзорники, которые увеличивают присутствие бренда в поиске и AI-ответах. Цена — $250 за сайт, предлагается стартовый пакет.",
    "Показать ценность сети сателлитов как канала (больше точек касания в выдаче и AI), назвать цену за сайт, предложить пакет, закрыть сделку.",
    "Head of Marketing, конкурентно настроен, спешит. Хочет быстро понять цифры — сколько сайтов нужно, сколько это стоит всего, когда будет результат. Торопится, хочет конкретики без долгих объяснений.",
    [("We've already run this exact setup for two other clients — it's one of the fastest ways to add extra brand touchpoints in search and AI answers.",
      "Мы уже делали точно такую же настройку для двух других клиентов — это один из самых быстрых способов добавить точки касания с брендом в поиске и AI."),
     ("Each site is $250, and we'd recommend starting with a package of 10 to get a real network effect.",
      "Каждый сайт — $250, рекомендуем начать с пакета из 10, чтобы получить реальный сетевой эффект."),
     ("The first sites usually start showing traffic within 4-6 weeks, citations follow shortly after.",
      "Первые сайты обычно начинают давать трафик через 4-6 недель, цитирования — чуть позже."),
     ("This sits outside the current retainer — it's a one-time build fee per site plus light monthly maintenance.",
      "Это отдельно от текущего ретейнера — разовая оплата за сборку каждого сайта плюс лёгкая ежемесячная поддержка."),
     ("If we lock this in today, the first batch can be live within two weeks.",
      "Если зафиксируем сегодня, первая партия будет запущена в течение двух недель."),
     ("Want me to reserve the 10-site package now so we can kick off this week?",
      "Зафиксировать пакет из 10 сайтов сейчас, чтобы начать на этой неделе?")],
    [("How many sites do we actually need to see a real difference?",
      "Сколько сайтов реально нужно, чтобы увидеть разницу?"),
     ("What's the total for 10 — is there a volume discount?",
      "Сколько всего за 10 — есть скидка за объём?"),
     ("How fast will this actually move the needle?",
      "Как быстро это реально даст результат?"),
     ("Can we start smaller and scale up if it works?",
      "Можем начать с меньшего и масштабировать, если сработает?"),
     ("Just give me the bottom line — what do I sign, and when do we start?",
      "Просто дайте итог — что подписывать и когда начинаем?"),
     ("Can you commit to this paying off within the quarter?",
      "Можете гарантировать, что это окупится в течение квартала?")],
  )),
  dict(title="Ranked but Invisible", sub="D · Стратегические сдвиги · переход с SEO на GEO", body=scenario_body(
    "B2B edtech — платформа корпоративного обучения (&laquo;SkillForge&raquo;)",
    "Классический трафик по информационным запросам падает — пользователи получают ответ прямо в AI Overviews / ChatGPT без клика. Бренд SkillForge почти не упоминается в AI-ответах, хотя раньше был в топ-3 по многим запросам.",
    "Объяснить сдвиг (падение трафика не из-за пенализации, а из-за смены поведения пользователей), предложить GEO-надстройку как расширение текущего SEO-пакета, а не замену.",
    "VP Marketing, привязан к старым метрикам — клики и позиции. Обеспокоен падением трафика в GSC, воспринимает GEO как «модное слово».",
    [("Your rankings are actually fine — the traffic decline is coming from AI Overviews answering the query directly.",
      "Ваши позиции в порядке — падение трафика происходит потому, что AI Overviews отвечает на запрос напрямую."),
     ("GEO isn't a replacement for SEO — it's making sure you're the source AI systems pull from and cite.",
      "GEO — это не замена SEO, это гарантия того, что именно вас AI-системы берут в качестве источника и цитируют."),
     ("Even without a click, being cited by name in an AI answer still drives brand awareness and trust.",
      "Даже без клика, упоминание по имени в AI-ответе всё равно повышает узнаваемость и доверие к бренду."),
     ("We'd restructure key pages for extractability — clear entities, self-contained answers, structured data.",
      "Мы перестроим ключевые страницы под извлекаемость — чёткие сущности, самодостаточные ответы, структурированные данные."),
     ("Let's track AI citations as a new metric alongside rankings, not instead of them.",
      "Давайте отслеживать AI-цитирования как новую метрику наряду с позициями, а не вместо них.")],
    [("If there's no click, how does this actually help our business?",
      "Если нет клика, как это реально помогает нашему бизнесу?"),
     ("Is this just a rebrand of SEO to charge us more?",
      "Это просто ребрендинг SEO, чтобы брать с нас больше денег?"),
     ("How do we even measure success if it's not rankings or traffic?",
      "Как мы вообще измеряем успех, если это не позиции и не трафик?"),
     ("Our competitors aren't talking about GEO — why should we invest now?",
      "Наши конкуренты не говорят про GEO — почему нам инвестировать сейчас?"),
     ("Can we wait and see if this is even a real trend?",
      "Можем подождать и посмотреть, реальный ли это тренд?")],
  )),
]

intro_block = '''<div class="info-card">
      <p class="idea">Работа в парах: один играет Специалиста, другой — Клиента. 5–7 минут на сценарий. Без подготовки — чистая импровизация.</p>
    </div>'''

scenarios_sec = section("scenarios", "Upsell Roleplay: сценарии для практики в группе",
                         "категория A — расширение каналов, B — новые направления, C — экспансия, D — стратегические сдвиги",
                         intro_block + accordion(scenarios, first_open=False))

body = f'''{vocab_sec}
{phrases_sec}
{scenarios_sec}'''

html = page(
    title="Урок 14 — Допродажа во время звонка",
    desc="Upselling & Cross-Selling in SEO Client Calls: словарь по апселлингу, фразы для мягкой допродажи на звонке и 8 ролевых сценариев по категориям.",
    brand="Global English · Урок 14",
    eyebrow="Урок 14 из курса «Global English для SEO»",
    h1="Допродажа во время звонка",
    lede="Как естественно предложить клиенту дополнительную услугу на звонке — опираясь на результат, без давления и с готовыми ответами на возражения.",
    navlinks=[("#vocab", "Словарь"), ("#phrases", "Фразы"), ("#scenarios", "Сценарии")],
    body=body,
    prev_href="/lessons/13/", prev_label="← Урок 13: Rendering & Page Speed",
    next_href="/lessons/15/", next_label="Урок 15: Сателлиты в SEO →",
)
write("lessons/14/index.html", html)
